### ISSUE TITLE
大佬，有将模型导出为 .onnx 的脚本吗

### ISSUE THREAD

**Issue by yechens** [qinggangwu/yolov7-pose_Npoint_Ncla#8]
官方的 export.py 脚本似乎不能兼容我们的代码

**Comment by yechens** [comment]
Problem solved

**Comment by yechens** [comment]
Problem solved

**Comment by wzy0903** [comment]
你好，你解决了吗，怎么导出和用opencv推理呀

**Comment by RunpuWei** [comment]
> 你好，你解决了吗，怎么导出和用opencv推理呀

utils/general.py 代码内，将non_max_suppression_export()方法的nkpt参数修改为关键点的个数。
